### ISSUE TITLE
How can I get the UITableViewCell when I use didSelectSubRowAtIndexPath

### ISSUE THREAD

**Issue by cnzlh** [sakkaras/SKSTableView#21]
- (void)tableView:(SKSTableView *)tableView didSelectSubRowAtIndexPath:(NSIndexPath *)indexPath 
  {
  MyCustomCell *cell = (MyCustomCell *)[tableView cellForRowAtIndexPath:indexPath];
  NSLog(@"%@",NSStringFromClass([cell class]));
  
  [cell customMethod];

}

However the cell Calss is SKSTableViewCell . can anyone help me?

**Comment by samiramin** [comment]
This is awesome, please integrate with the original code, It is very helpful
